### ISSUE TITLE
Improve this

### ISSUE THREAD

**Issue by PaoloFalomo** [tholman/bsod.js#2]
You should improve this by:
- [**Detecting the windows versio**n](http://stackoverflow.com/questions/4006420/detect-windows-version-with-javascript) (bc BSOD changed along them, because we obv need a new design to show us our computer just blowed up. Yeah! Thank you microsoft.) 
- Fire the **fullscreen** for a more _realistic_ aspect

Cheers!

**Comment by tholman** [comment]
Haha, love it! Going to close this off though, feel like the project is complete and on point 💃
